### ISSUE TITLE
Add back Security and Surveillance apps to Hospital wards

### ISSUE THREAD

**Issue by xRunePT** [Arsonide/GovernmentLockdown#1]
Heya, sorry if this isn't the right place for this but I couldn't find another way.
I just wanted to suggest adding back those apps to the hospital wards. I love everything else but I find it weird that there's cameras in those places and now there's absolutely no way to access them, since the apps in the Enforcer areas only cover the cameras in their areas.
Even just a config option for it would do.
I had a murder case in the Hospital and I was so confused why I couldn't see the footage.

If I missed something and I can still access the Hospital cameras, then let me know please.

**Comment by Arsonide** [comment]
Solved in release 0.8.2. I added config options to re-enable these apps on unsecure city hall crunchers.
